2023-04-13 03:10:10.559 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-04-13 03:10:16.600 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Iris for spotify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/spotify/__init__.py", line 74, in async_setup_entry
    implementation = await async_get_config_entry_implementation(hass, entry)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 401, in async_get_config_entry_implementation
    raise ValueError("Implementation not available")
ValueError: Implementation not available
2023-04-13 03:10:42.106 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WLED' for wled integration not ready yet: Invalid response from API: Timeout occurred while connecting to WLED device at 192.168.15.102; Retrying in background
2023-04-13 03:10:42.127 WARNING (Recorder) [homeassistant.components.recorder.migration] Database is about to upgrade from schema version: 41 to: 35
2023-04-13 03:23:13.000 ERROR (MainThread) [homeassistant.components.nws] Error requesting NWS forecast station KTAN data: 500, message='Internal Server Error', url=URL('https://api.weather.gov/gridpoints/BOX/76,74/forecast')
2023-04-15 21:50:23.601 WARNING (MainThread) [homeassistant.components.automation.10secperiodictimer] 10SecPeriodicTimer: Already running
2023-04-15 21:53:25.012 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:53:25.018 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:53:35.011 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:53:35.017 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:53:45.013 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:53:45.021 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:53:55.015 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:53:55.019 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:05.007 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:05.011 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:15.014 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:15.017 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:25.015 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:25.019 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:35.008 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:35.012 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:45.013 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:45.016 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:54:55.014 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:54:55.017 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:05.020 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:05.025 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:15.010 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:15.015 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:25.010 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:25.014 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:35.010 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:35.013 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:45.010 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:45.015 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:55:55.011 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:55:55.014 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:56:05.013 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] RandomTempAuto: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['value']
2023-04-15 21:56:05.020 ERROR (MainThread) [homeassistant.components.automation.randomtempauto] Error while executing automation automation.randomtempauto: expected float for dictionary value @ data['value']
2023-04-15 21:59:22.606 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'input_number' is undefined when rendering '{"sessionId": "{{trigger.event.data._intent.sessionId}}", text" : "The temperature is {{input_number.room_temperature_f}} degrees"}'
2023-04-15 21:59:22.626 ERROR (MainThread) [homeassistant.components.automation.gettemperature] GetTemperature: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'input_number' is undefined
2023-04-15 21:59:22.628 ERROR (MainThread) [homeassistant.components.automation.gettemperature] Error while executing automation automation.gettemperature: Error rendering data template: UndefinedError: 'input_number' is undefined
2023-04-15 22:00:39.807 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'input_number' is undefined when rendering '{"sessionId": "{{trigger.event.data._intent.sessionId}}", text" : "The temperature is {{states(input_number.room_temperature_f)}} degrees"}'
2023-04-15 22:00:39.809 ERROR (MainThread) [homeassistant.components.automation.gettemperature] GetTemperature: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'input_number' is undefined
2023-04-15 22:00:39.815 ERROR (MainThread) [homeassistant.components.automation.gettemperature] Error while executing automation automation.gettemperature: Error rendering data template: UndefinedError: 'input_number' is undefined
